import { expect, test } from "@playwright/test"
import { readFileSync } from "node:fs"
import path from "node:path"
import url from "node:url"

// The branching-logic evaluator parity harness (REQ-TECH-028). Data_Validation_Design.md §7.3
// fixes one normative semantics for every evaluator; this spec runs web/assets/js/branching.js
// over the same corpus the Go tests hold api/internal/validate/expr.go to
// (api/internal/validate/testdata/branching_corpus.json, generated by
// TestGenerateBranchingCorpus). A case that moves one side must move the corpus — never one
// evaluator alone. Pure module test: no server and no page needed; smoke.spec.mjs already
// proves the engine runs vanilla ES2020 untranspiled.
//
// .mjs so Node loads it as ESM (the package is CJS by default); the module under test has no
// imports of its own, so it is imported from its source text as a data: URL — the same ES2020
// the browser receives through <script type="module">.

const here = path.dirname(url.fileURLToPath(import.meta.url))
const source = readFileSync(path.resolve(here, "../../web/assets/js/branching.js"), "utf8")
const { compileBranching, branchingRefs } = await import(
  "data:text/javascript;base64," + Buffer.from(source).toString("base64")
)

const corpus = JSON.parse(
  readFileSync(
    path.resolve(here, "../../api/internal/validate/testdata/branching_corpus.json"),
    "utf8"
  )
)

// The environment mirrors Go's LogicEval: value/choices resolve a reference by its
// (event, field) pair; an absent read is "". The [field] shorthand arrives with an empty event.
function envFor(cs) {
  const values = cs.values ?? {}
  const choices = cs.choices ?? {}
  return {
    value: (event, field) => values[event + "|" + field] ?? "",
    choices: (event, field) => choices[event + "|" + field] ?? "",
  }
}

for (const cs of corpus) {
  test(cs.name, async () => {
    if (cs.want_err) {
      expect(() => compileBranching(cs.expr)).toThrow()
      return
    }
    expect(compileBranching(cs.expr).evaluate(envFor(cs))).toBe(cs.expected)
  })
}

test("branchingRefs lists referenced fields in first-seen order, deduplicated", async () => {
  const refs = branchingRefs(`[e1][a] = 1 && [b] && text_contains([e1][c], "x") || [e1][a]`)
  expect(refs).toEqual([
    { event: "e1", field: "a" },
    { event: "", field: "b" },
    { event: "e1", field: "c" },
  ])
})
